//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Lib.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSubscription
    {
        public int CustomerId { get; set; }
        public string Subscription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Subscription Subscription1 { get; set; }
    }
}
